set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(RV1126B_SDK_ROOT "/opt/aarch64-buildroot-linux-gnu_sdk-buildroot" CACHE PATH "RV1126B Buildroot SDK root")
set(RV1126B_CROSS_PREFIX "aarch64-buildroot-linux-gnu-" CACHE STRING "RV1126B compiler prefix")

set(CMAKE_SYSROOT "${RV1126B_SDK_ROOT}/aarch64-buildroot-linux-gnu/sysroot" CACHE PATH "RV1126B sysroot")

set(CMAKE_C_COMPILER "${RV1126B_SDK_ROOT}/bin/${RV1126B_CROSS_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${RV1126B_SDK_ROOT}/bin/${RV1126B_CROSS_PREFIX}g++")
set(CMAKE_ASM_COMPILER "${RV1126B_SDK_ROOT}/bin/${RV1126B_CROSS_PREFIX}gcc")
set(CMAKE_AR "${RV1126B_SDK_ROOT}/bin/${RV1126B_CROSS_PREFIX}ar")
set(CMAKE_RANLIB "${RV1126B_SDK_ROOT}/bin/${RV1126B_CROSS_PREFIX}ranlib")
set(CMAKE_STRIP "${RV1126B_SDK_ROOT}/bin/${RV1126B_CROSS_PREFIX}strip")

set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_VERBOSE_MAKEFILE ON)
