set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(RV1126B_CROSS_PREFIX "aarch64-buildroot-linux-gnu-" CACHE STRING "RV1126B compiler prefix")

set(CMAKE_C_COMPILER "${RV1126B_CROSS_PREFIX}gcc")
set(CMAKE_CXX_COMPILER "${RV1126B_CROSS_PREFIX}g++")
set(CMAKE_ASM_COMPILER "${RV1126B_CROSS_PREFIX}gcc")
set(CMAKE_AR "${RV1126B_CROSS_PREFIX}ar")
set(CMAKE_RANLIB "${RV1126B_CROSS_PREFIX}ranlib")
set(CMAKE_STRIP "${RV1126B_CROSS_PREFIX}strip")

if(NOT CMAKE_SYSROOT)
    execute_process(
        COMMAND ${CMAKE_C_COMPILER} --print-sysroot
        OUTPUT_VARIABLE _RV1126B_SYSROOT
        OUTPUT_STRIP_TRAILING_WHITESPACE
        RESULT_VARIABLE _RV1126B_SYSROOT_RC
    )
    if(_RV1126B_SYSROOT_RC EQUAL 0 AND EXISTS "${_RV1126B_SYSROOT}")
        set(CMAKE_SYSROOT "${_RV1126B_SYSROOT}" CACHE PATH "RV1126B sysroot (auto-detected)")
        set(CMAKE_FIND_ROOT_PATH "${CMAKE_SYSROOT}")
    else()
        message(WARNING "无法从 ${CMAKE_C_COMPILER} 自动探测 sysroot，"
                        "请确认工具链已加入 PATH，或手动指定 CMAKE_SYSROOT。")
    endif()
    unset(_RV1126B_SYSROOT)
    unset(_RV1126B_SYSROOT_RC)
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_VERBOSE_MAKEFILE ON)
